# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 091acecb9b725a3b94fef375da9cc6748bf58768d1aed3b67d356d057ed954580c0b88b3650ede9d04b36e1a04646ee6c918f04fc4687843c121d1f21515a5d7

test:
  secret_key_base: fc7cc6a9051820d1ed21ebf8d08fb16ce623ca25c28163464ed9d32f9bec8ed138108466aae042f6550f9f385c86c5376e6b7c0748e456ed6fcffb9bf08924c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
